//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SomeLanguage.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SomeLanguageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ISomeLanguageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SomeLanguageParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] SomeLanguageParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SomeLanguageParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] SomeLanguageParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SomeLanguageParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] SomeLanguageParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SomeLanguageParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] SomeLanguageParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SomeLanguageParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod([NotNull] SomeLanguageParser.MethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SomeLanguageParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod([NotNull] SomeLanguageParser.MethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SomeLanguageParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodName([NotNull] SomeLanguageParser.MethodNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SomeLanguageParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodName([NotNull] SomeLanguageParser.MethodNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SomeLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] SomeLanguageParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SomeLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] SomeLanguageParser.InstructionContext context);
}
