//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntlrTestCsharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntlrTestCsharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMD5HashData
        ///GetSHA1HashData
        ///ValidateMD5HashData
        ///ValidateSHA1HashData.
        /// </summary>
        internal static string BadCrypto {
            get {
                return ResourceManager.GetString("BadCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlCommand
        ///SqlDataAdapter.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteNonQuery
        ///ExecuteNonQueryAsync
        ///ExecuteReader
        ///ExecuteReaderAsync
        ///ExecuteScalar
        ///ExecuteScalarAsync
        ///ExecuteXmlReader
        ///ExecuteXmlReaderAsync
        ///executequery.
        /// </summary>
        internal static string ExecuteSQL {
            get {
                return ResourceManager.GetString("ExecuteSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +:+
        ///{0}:,.
        /// </summary>
        internal static string SpecialCase {
            get {
                return ResourceManager.GetString("SpecialCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ProhibitDtd=true
        ///.XmlResolver=null
        ///.DtdProcessing=DtdProcessing.Prohibit.
        /// </summary>
        internal static string VulnContext {
            get {
                return ResourceManager.GetString("VulnContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlReaderSettings
        ///XmlTextReader
        ///XmlDocument.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
